
backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Leheküljed"
    files:
      - file: "index.html"
        label: "Avaleht"
        name: "avaleht"
        fields:
          - { label: "Pealkiri", name: "title", widget: "string" }
          - { label: "Sisu", name: "content", widget: "markdown" }
